version: "3.1"

services:
  django:
    container_name: django
    build:
      dockerfile: ./Dockerfile.backend
    restart: unless-stopped
    command: sh ./backend-entrypoint.sh
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres:17.4-alpine3.21
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=city_party
    container_name: pgdb
    restart: unless-stopped
    ports:
      - "5432:5432"

  nginx:
    container_name: nginx
    build:
      dockerfile: ./Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
    restart: unless-stopped