services:
  django:
    container_name: django
    build:
      dockerfile: ./Dockerfile.backend
    restart: unless-stopped
    command: sh ./backend-entrypoint.sh
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - redis
    env_file:
      - .env

  pgdb:
    image: postgres:17.4-alpine3.21
    environment:
      - POSTGRES_PASSWORD=acRGU
      - POSTGRES_USER=postgres
      - POSTGRES_DB=city_party
    container_name: pgdb
    restart: unless-stopped
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.11-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  nginx:
    container_name: nginx
    build:
      dockerfile: ./Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
      - ./media:/app/media/
    depends_on:
      - django
    restart: unless-stopped