# Generated by Django 5.1.6 on 2025-03-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл'),
        ),
    ]
