# Generated by Django 5.1.4 on 2025-06-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Дата начала'),
        ),
    ]
