# Generated by Django 5.1.6 on 2025-03-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ticket_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vk_profile',
            field=models.URLField(blank=True, null=True, verbose_name='ВК-профиль'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
    ]
