# Generated by Django 5.1.4 on 2025-06-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tickettype_end_date_tickettype_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Не оплачен'), ('paid', 'Оплачен'), ('canceled', 'Отменен'), ('on_canceled', 'На возврате')], default='pending', verbose_name='Статус оплаты'),
        ),
    ]
