# Generated by Django 5.1.6 on 2025-02-17 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cover_image',
        ),
    ]
