# Generated by Django 5.1.4 on 2025-06-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ticket_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
    ]
