# Generated by Django 5.1.6 on 2025-03-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_vk_profile_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='vk_profile',
            field=models.URLField(blank=True, null=True, verbose_name='ВК профиль'),
        ),
    ]
