# Generated by Django 5.1.6 on 2025-02-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_event_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='description',
            field=models.TextField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
