# Generated by Django 5.1.6 on 2025-02-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_review_event'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
    ]
