# Generated by Django 5.1.6 on 2025-02-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_event_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table='banners',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='company',
            table='companies',
        ),
        migrations.AlterModelTable(
            name='place',
            table='places',
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='tickets',
        ),
        migrations.AlterModelTable(
            name='tickettype',
            table='ticket_types',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
