# Generated by Django 5.1.6 on 2025-02-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_banner_table_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gallery',
            table='galleries',
        ),
    ]
