# Generated by Django 5.1.6 on 2025-02-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_gallery_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
    ]
