# Generated by Django 5.1.6 on 2025-02-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галереи'},
        ),
    ]
