# Generated by Django 5.1.6 on 2025-02-19 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_event_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 9, 22, 50, 24178, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-pub_date'], name='events_pub_dat_8e430e_idx'),
        ),
    ]
