# Generated by Django 5.1.6 on 2025-02-19 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_event_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 9, 37, 39, 301356, tzinfo=datetime.timezone.utc)),
        ),
    ]
