# Generated by Django 5.1.6 on 2025-02-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_event_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
