# Generated by Django 5.1.6 on 2025-02-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_tickettype_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='available_quantity',
            new_name='available_quantityy',
        ),
        migrations.RenameField(
            model_name='tickettype',
            old_name='event_date',
            new_name='event_datee',
        ),
        migrations.RenameField(
            model_name='tickettype',
            old_name='total_quantity',
            new_name='total_quantityy',
        ),
    ]
