# Generated by Django 5.1.6 on 2025-02-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_available_quantityy_tickettype_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='event_date',
            field=models.DateField(),
        ),
    ]
