# Generated by Django 5.1.6 on 2025-02-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_banner_company_alter_banner_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='available_quantity',
        ),
    ]
