# Generated by Django 5.1.6 on 2025-02-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_tickettype_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='available_quantity',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Доступное количество'),
        ),
    ]
