# Generated by Django 5.1.6 on 2025-02-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_tickettype_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tin',
            field=models.PositiveBigIntegerField(default=0, verbose_name='ИНН'),
            preserve_default=False,
        ),
    ]
