# Generated by Django 5.1.6 on 2025-02-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_company_tin'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(default=0, max_length=100, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
