# Generated by Django 5.1.6 on 2025-02-21 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_ticket_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 21, 13, 20, 28, 606986, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='event_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата события'),
        ),
    ]
