# Generated by Django 5.1.6 on 2025-02-25 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_banner_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
