# Generated by Django 5.1.6 on 2025-02-25 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('rejected', 'Отклонен'), ('accepted', 'Принят'), ('on moderation', 'На модерации')], default='on moderation', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Не оплачен'), ('paid', 'Оплачен'), ('canceled', 'Отменен')], default='pending', verbose_name='Статус оплаты'),
        ),
    ]
