# Generated by Django 5.1.6 on 2025-02-25 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_review_status_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='app.event', verbose_name='Ивент'),
        ),
    ]
