# Generated by Django 5.1.6 on 2025-02-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_banner_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Видимость'),
        ),
    ]
