# Generated by Django 5.1.6 on 2025-02-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_event_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_pub_dat_8e430e_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pub_date',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-created_at'], name='events_created_fc135f_idx'),
        ),
    ]
