# Generated by Django 5.1.6 on 2025-02-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_place_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
