# Generated by Django 5.1.6 on 2025-02-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_place_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cover_image',
        ),
    ]
