# Generated by Django 5.1.6 on 2025-02-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='cover_image',
        ),
    ]
