# Generated by Django 5.1.6 on 2025-02-25 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_rename_image_event_cover_image'),
        ('photologue', '0014_alter_watermark_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.gallery', verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.photo', verbose_name='Обложка'),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
