# Generated by Django 5.1.6 on 2025-02-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_event_gallery_alter_event_cover_image_delete_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at', 'is_published'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
    ]
