# Generated by Django 5.1.6 on 2025-02-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_event_options'),
        ('photologue', '0014_alter_watermark_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_created_fc135f_idx',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='events_created_9e2206_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_published'], name='events_is_publ_8cb0a3_idx'),
        ),
    ]
