# Generated by Django 5.1.6 on 2025-02-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['created_at'], name='banners_created_9e788a_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['event'], name='banners_event_i_ebc543_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['created_at'], name='places_created_9fc069_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['is_published'], name='places_is_publ_ea423f_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['author'], name='reviews_author__db9630_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['event'], name='reviews_event_i_dc2123_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='reviews_created_53b5d6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status'], name='reviews_status_12ddaa_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['owner'], name='tickets_owner_i_70c82f_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['event_date'], name='ticket_type_event_d_9b2953_idx'),
        ),
    ]
