# Generated by Django 5.1.6 on 2025-03-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('rejected', 'Отклонен'), ('accepted', 'Принят'), ('on_moderation', 'На модерации')], default='on_moderation', verbose_name='Статус'),
        ),
    ]
